# Generated by Django 4.2.5 on 2023-10-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_location_meetup_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='Location',
            new_name='location',
        ),
    ]
