# Generated by Django 4.2.5 on 2023-10-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_meetup_date_meetup_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='participant',
            new_name='participants',
        ),
    ]
